version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  
  build:
    commands:
      - echo "Building the Spring Boot application..."
      - ./mvnw package

artifacts:
  files:
    - target/*.jar
  discard-paths: yes